#!/usr/bin/env bash
#Bash (init) script 101-manage_my_process that manages manage_my_process.
#Read:

#    &
#    init.d
#    Daemon
#    Positional parameters

#man: sudo

#Programs that are detached from the terminal and running in the background are called daemons or processes, need to be managed. The general minimum set of instructions is: start, restart and stop. The most popular way of doing so on Unix system is to use the init scripts.

#Write a manage_my_process Bash script that:

#    Indefinitely writes I am alive! to the file /tmp/my_process
#    In between every I am alive! message, the program should pause for 2 seconds

#Write Bash (init) script 101-manage_my_process that manages manage_my_process. (both files need to be pushed to git)

if [ "${1}" == "start" ]
then
    ./manage_my_process &
    touch /var/run/my_process.pid
    echo "$!" > /var/run/my_process.pid
    echo "manage_my_process started"
elif [ "${1}" == "stop" ]
then
    echo "manage_my_process stopped"
    kill "$(cat /var/run/my_process.pid)"
    rm /var/run/my_process.pid
elif [ "${1}" == "restart" ]
then
    kill "$(cat /var/run/my_process.pid)"
    rm /var/run/my_process.pid
    ./manage_my_process &
    touch /var/run/my_process.pid
    echo "$!" > /var/run/my_process.pid
    echo "manage_my_process restarted"
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi


