#!/usr/bin/env bash
# Parses Apache log files in list format.
#   Displays the IP and HTTP status code.
#Requirement:

#    Format: IP HTTP_CODE
#        in a list format
#        See example
#    You must use awk
#    You are not allowed to use while, for, until and cut
#    Download and commit the apache-access.log file along with your answers files
	
awk '{print $1 " " $9}' apache-access.log


