#!/usr/bin/env bash
# Parses Apache log files in list format.
#   Groups visitors by IP and HTTP status code.
#   Displays the number of occurrences, IP, and HTTP status
#Requirements:

#    The exact format must be:
#    OCCURENCE_NUMBER IP HTTP_CODE
#    In list format
#    Ordered from the greatest to the lowest number of occurrences
#    You must use awk

awk '{ print $1 " " $9}' apache-access.log | sort | uniq -c | sort -rn
