#!/usr/bin/env bash
# script that displays best School 10 times, but for the 9th iteration,
#+ displays best School and then Hi on a new line.

i=0
while [ $i -le 10 ]; do
	echo "best School"
	if [ $i -eq 9 ]; then
		echo "Hi";
	fi
	let "i++";
done
