#!/usr/bin/env bash
# script that displays best School 10 times, but for the 9th iteration,
#+ displays best School and then Hi on a new line.

ct=0

while [ $ct -lt 10 ]
do
  if [ $ct -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( ct++ ))
done

